language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install busted

install:
  - luarocks make

script:
  - busted */spec.lua
